---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celery-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - args:
            - celery
            - -A
            - app
            - worker
            - -l
            - info
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: env-dev
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: env-dev
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  key: DB_PASS
                  name: env-dev
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: env-dev
          image: celery
          name: celery
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: celery-claim0
      restartPolicy: Always
      volumes:
        - name: celery-claim0
          persistentVolumeClaim:
            claimName: celery-claim0
status: {}

